### ISSUE TITLE
Are NLTE calculations broken?

### ISSUE THREAD

**Issue by ParfenovS** [lime-rt/lime#261] opened 2018-02-22 11:29 UTC
It is interesting that the current LIME version gives results for the example model that are significantly different from those that can be obtained with earlier versions. The following is the J=5 level population fraction vs cloud radius for the current and old LIME (with the most of the bugs fixed) versions in the example model.

![example_model](https://user-images.githubusercontent.com/13845610/36535542-dddaf3de-17eb-11e8-93be-f10365543150.png)

I have no idea when and why such a difference had appeared.
Such a difference in level populations leads to a significant difference in the predicted images and spectra. The old images can be found, for example, here #95 . The difference in flux densities is about factor of two. It is well known that old LIME versions allowed to obtain the results which were in a good agreement with the benchmarks of van Zadelhoff et al. (2002). I'm not sure that the same is true for the current LIME version.
The biggest problem is that with the current LIME version it was impossible for me to obtain reasonable results for the 2a or 2b models of van Zadelhoff et al. (2002). The populations of the most levels in the most cloud points are just of 1.e-30.

**Comment by allegroLeiden** [comment] 2018-02-23 15:45
I agree there are worrying issues with the numbers LIME produces. I have spent the majority of my time over the last couple of years first in finding and fixing numerous code traps and other tangles in LIME, and secondly in adding the python/CASA interfaces which is what I was mostly employed here to do. Tuomas and I have tried not to make any changes in the algorithm beyond fixing some obvious errors, but it seems that the major overhaul the code has undergone has introduced some inadvertent changes. Alas, I'm coming to the end of my contract soon, I'm actively looking for jobs, thus the amount of time I'm going to be able to devote to LIME will shrink away to nothing just as soon as I get another job. I would hope that whoever takes over responsibility for it would commence a careful, painstaking program of test-and-fix for the numerical results, since this is now sorely needed.

**Comment by cleevesli** [comment] 2018-02-23 15:52
@ParfenovS, what was the last version where the example model benchmark agreed? @allegroLeiden thank you (!!!) for your efforts! The speed improvements and better-looking image outputs have been especially appreciated!

**Comment by danharsono** [comment] 2018-02-23 16:05
@ParfenovS Thanks for the update on this particular problem. Could you please clarify how you did you implement the van Zadelhoff et al. 2002? Also which collisional rate coefficients did you use for these calculations? 
For problems 1 and 2, I find them to be sufficiently accurate given that the grids are the same. 
![fig14c](https://user-images.githubusercontent.com/12612390/36603622-aaee82e4-18bb-11e8-94a6-08ed67bb021f.png)
![fig16c](https://user-images.githubusercontent.com/12612390/36603638-b8193fae-18bb-11e8-8048-8248252ee060.png)
These are the comparison with RATRAN.

**Comment by ParfenovS** [comment] 2018-02-23 16:24
I can only join to @cleevesli and thank @allegroLeiden for the work.

>what was the last version where the example model benchmark agreed?
I don't know exactly. I'm just using old files with populations generated with LIME version 1.6 (or close to that version). 

@danharsono thanks for the comparison. Please find the model and molecular data files for the van Zadelhoff et al. 2002 problem 2 here: https://www.dropbox.com/s/se699l70y5ne60b/model.zip?dl=0

**Comment by danharsono** [comment] 2018-02-23 16:38
@ParfenovS  Thanks for the model file. I believe that van Zadelhoff et al. 2002 used a slightly different collisional rates coefficients. It is more instructive to re-do the test with a different code such as RATRAN. Also to read the same grid: ie. from 0.1au to 2.0 au density = x.  The density in LIME should also be a step function.  Note that the inner regions of LIME deviate from that of RATRAN but the rest should be fine. 
Below is the comparison of the images for problem 2: 
![fig15c](https://user-images.githubusercontent.com/12612390/36604940-79629a04-18bf-11e8-9d20-cea62ba39589.png)
For the set of tests I have done, I always find the v=0 tend to deviate from results obtained with other codes.  However, with convolution, the line profile and the fluxes are fine.  The v=0 image can be improved if smaller velocity steps are taken and then binned to match the observations. But, to be continued on that... 

I have a  few more tests to do and will post them in due time. Please do not compare problems 3 and 4 yet. Those show the largest deviation.

**Comment by ParfenovS** [comment] 2018-02-23 16:51
@danharsono the collisional rates are the same. With the same molecular datafile and model.c (i.e. density, temperature etc. functions) file I was able to obtain a good agreement with benchmarks using old LIME versions. The results were close to those presented by C. Brinch at the end of thread #147

**Comment by ParfenovS** [comment] 2018-02-23 18:02
Hm, interesting. By the current LIME version I meant the one that can be obtained with github "Clone or download" button. So, this is the current master branch (which will probably be the future version 1.9.2). It appears that this master-branch version is somewhat broken. The release versions are fine.
The following is the comparison of the level populations obtained with the LIME release versions 1.7.3, 1.9.1 and the current master-branch version:
![pops](https://user-images.githubusercontent.com/13845610/36608964-458a0c2a-18ed-11e8-83d4-08c52f36dda8.png)

The difference is the same as in my first plot.

**Comment by ParfenovS** [comment] 2018-02-24 04:30
@allegroLeiden ,
I'm planning to upload at github my fork of LIME which is based mainly on LIME versions < 1.7. The main features of the fork are that photons travel along straight lines (and, consequently, there are no sink points), there is no python support, there is MPI support, more full support of simultaneous calculations with different molecules, support of calculations with several grain opacities.
The main questions are should I rename the program and how should I change license agreement.
I'm sorry for hesitating you and littering this thread. It is more comfortable for me to ask you first.

**Comment by danharsono** [comment] 2018-02-24 06:56
@ParfenovS Interesting. Thanks for pointing out that the problem is in the current mater version.

**Comment by allegroLeiden** [comment] 2018-02-26 08:46
Hi all, thanks very much for your useful input. I've been worried about this and I wanted to do some benchmark checks before the next release (which would be 1.10). It is interesting but also somewhat encouraging that the master track deviates from the last release - this would tend to point to some single-point change which has introduced a bug. I'll see if I can find it as soon as I can get back to this. @ParfenovS , I'm not sure what best to recommend to you re your planned PR. As far as merging the code goes, I foresee problems, because there has been substantial reshuffling of functions between the code modules between 1.7 and the latest release. I also have a big wodge of code waiting in the wings, which implements all the python/CASA support I plan ever to approach. This is currently in the 'mycasa' branch of my fork of Lime. I was going to raise a PR on this as soon as I (i) did a bit of benchmark-style checking and (ii) updated the documentation. I wanted to release this pretty soon after as 1.10. As soon as that is done, I could sign off on my CASA interface mission, and I would at that point personally be more comfortable with looking at improving the functionality and speed of Lime re your suggested PR.

Photons travelling on straight lines is probably a better way to approach things, however this is a major departure in the algorithm. Maybe we could work out some way to retain a choice of algorithms?

Re the licence agreement, what sort of changes did you have in mind? Licensing is not something I have paid a lot of attention to, since I know that whoever holds the IPR, it certainly isn't me. :) Michiel Hogerheijde I think is of the opinion that Leiden holds them, since Christian was a student here when he wrote the code, but as you know, the published code includes the Gnu GPL, but also states that copyright resides in the Lime development team. So things seem a bit of a mess to me.

I should mention that I am currently looking at a version of Lime, based on some unspecified post-1.6.1 snapshot of the master track, written by W Homan and his students. This contains too many changes, and is based on too old a version of Lime, for a direct PR/merge to be possible. I was going to look at it and see if I could hack up a merge of some of its features post 1.10. Features include the addition of radiation sources and the possibility of several dust species.

**Comment by mcordiner** [comment] 2018-07-13 22:18
Sorry, I'm a bit confused - did this get fixed for the 1.9.2 release, or would I be better off using 1.9.1 for the time being?

**Comment by ParfenovS** [comment] 2018-07-16 07:35
@mcordiner , the 1.9.2 release is fine, you can use it.

**Comment by allegroLeiden** [comment] 2018-07-23 09:52
Found it. Swapped indices in line 767 of solver.c.

**Comment by allegroLeiden** [comment] 2018-07-24 06:53
Closed by #268.

**Closed** 2018-07-24 06:52 UTC
