### ISSUE TITLE
Raytracing is slow

### ISSUE THREAD

**Issue by christianbrinch** [lime-rt/lime#95] opened 2016-04-08 11:41 UTC
Raytracing in version 1.5 seems incredibly slow (5-10 times slower) compared to previous versions. What happened?

**Comment by ParfenovS** [comment] 2016-04-11 06:59
The main loop in previous version of raytracing procedure was through grid points. The main loop in the new version is through pixels and within this loop there is also "anti-aliasing" loop.
In the case of example model the number of pixels 100x100 and the number grid points is 7000. Thus, for the new version one needs par->antialias*10000=40000 steps and the old version requires 7000 steps.

**Comment by allegroLeiden** [comment] 2016-04-11 10:29
I don't know what version you are looking at Sergey, because the loop was over pixels in 1.3.1, which was where I came in. 1.5 should be faster than that because all the sines and coses are now precalculated, calls to pow(blah,2) replaced by multiplications etc.

**Comment by imckstewart** [comment] 2016-04-11 10:35
I guess I ought to comment as myself rather than 'allegroLeiden'... one big change since 1.3 is that the procedure of following each ray was placed in a separate function. I guess that will add some overhead. It is better coding practice but if it turns out to slow things down massively I guess we ought to back it out again.

**Comment by ParfenovS** [comment] 2016-04-11 10:36
Yes, raytracing in version 1.3 is almost the same as in version 1.5. I meant version 1.4. The code of raytracing procedure of version 1.4 can be found in raytrace.c file (raytrace_1_4 function).

**Comment by imckstewart** [comment] 2016-04-11 11:26
Ok yeah, I remember that. I put in a PR a while ago (don't know why SM hasn't accepted it) for a raytrace which used some elements of that algorithm, but mainly I wanted to have better handling for pixels where the number of grid points per pixel was high, rather than the opposite extreme, which would be where any speed issue would be. So maybe this is something worth a look at.

**Comment by tlunttil** [comment] 2016-04-19 11:39
I had a quick look at where all that time spent in raytracing goes. It seems that most (more than half at least) of the time is spent in calls to the user-defined "velocity" function. This is with the default model.c, where the velocity function isn't even that complicated. So short of decreasing the number of rays traced (by reducing samples per pixel, which would worsen image quality), there's probably not much to be done, unless the whole velocity integration stuff is done differently.

**Comment by allegroLeiden** [comment] 2016-04-19 11:50
The call to velocity() is a bit of a nuisance also because it compels the user to supply it. All the other user-supplied functions can (at least potentially) be sampled elsewhere, the grid values then being supplied to Lime in the pregrid file. I have a PR in for a raytracing algorithm which basically does 1st-order finite-element method (FEM) interpolation inside the Delaunay tetrahedra, which smooths out the channel maps a lot, but I found I still had to call velocity() several times per cell to get a satisfying amount of smoothness. The problem is that the velocity can vary enough across a single cell, at least with the number density specified in the default model.c, to traverse a significant fraction of the spectral line. A linear interpolation of velocity within the cell thus leads to unacceptably large errors in integrating over the lineshape. Some time I want to try 2nd-order FEM of the populations, which might also be a high enough order approximation of the velocity.

**Comment by allegroLeiden** [comment] 2016-04-19 11:52
I think Christian also makes a good point however that the 1.4 algorithm, so far as I understand it, interpolates in the image planes between a relatively small number of rays. I think it is worth looking at this and seeing if we can't include it in the master branch some time.

**Comment by tlunttil** [comment] 2016-04-19 11:57
To add my previous comment, one very simple improvement that did speed up raytracing a bit is to add schedule(dynamic) after #pragma omp for on line 260 of raytrace.c. With default scheduling different threads finish at significantly different times, so all cores are not used efficiently.

**Comment by tlunttil** [comment] 2016-04-19 12:07
@allegroLeiden : by "1st-order FEM" do you mean piecewise linear interpolation inside each Delaunay tetrahedron? In that case you could (I think...) calculate the integrals analytically. That should also be doable when using higher degree polynomial interpolation, although it quickly becomes messier and messier...

**Comment by allegroLeiden** [comment] 2016-04-19 12:29
It is linear or 1st-order interpolation (1OI) between the vertex- or grid-values of the product nmol*binv*pops. FEM I guess is all about how you do it - it is a formalism which makes it very easy to extend the interpolation to higher orders. So for each ray, I locate the point at which it enters and exits the cell. I calculate n*b*p for those points via 1OI from the vertices. I then do 1OI between the entry and exit points for several places along the track through the cell, simply sample the line shape to get vfac, then add up the resulting alphas and jnus. The point is that also doing 1OI of the velocity values at the vertices does not give a good result - thus, for velocity, I call the user-supplied function at each sample point along the in-cell track. I hope that makes sense.

**Comment by tlunttil** [comment] 2016-04-19 13:03
Ok, I think I get it. What I was thinking about was that vfac is essentially convolution of the velocity distribution along the ray with a (fixed) Gaussian profile; if the velocity is polynomial along the ray (as it will be if we use polynomial interpolation inside each tetrahedron), we can work out the velocity distribution and its convolution with a Gaussian mostly explicitly, so there'd be no need for sub-stepping inside a tetrahedron. Some more thinking about this is still needed...

Now that I look at the code more closely, I realised we could dramatically reduce the number of calls to velocity() by rearranging the code so that we'd only poll velocity once for each position. Now it's done separately for every channel which is not necessary. The change is a bit difficult to do cleanly with how the code is currently structured, but surely much easier than my other idea.

**Comment by allegroLeiden** [comment] 2016-04-19 13:32
D'Oh!!! Missed that. Arrrgh, the pain. My only excuse is that I am concentrating on quality and robustness at the moment, rather than speed...

**Comment by tlunttil** [comment] 2016-05-27 11:05
So, if the number of image pixels is (significantly) larger than number of grid points, version 1.4 raytracing is a lot faster. I'm not sure how much sense it makes to have a high-resolution image of a low-resolution model, but maybe there are cases where this is useful.

Anyway, if raytracing_1_4 is included (as an option) in 1.6, there are a few of things to consider:

-  Apparently there's a bug on line 505 (mb): instead of `z1=rays[zt[2]].intensity[ichan];` I think it should be `z1=rays[zt[0]].intensity[ichan];`.
- Calculation of `d1, d2, d3, di` could be taken out of the channel loop (though it's probably already done by compiler).
- Parallelisation of raytracing and interpolation loops, which should be very easy.
 
The whole interpolation algorithm itself seems kinda strange to me, for example the interpolant is not continuous across the triangle boundaries. I think something simple such as piece-wise linear interpolation would be better. However, the basic idea of building the image with image plane interpolation from a smallish number of rays instead of pixel-by-pixel raytracing could have some advantages besides (in some cases) better performance. For example the image would automatically be smooth (with a suitable interpolation algorithm).

**Comment by tlunttil** [comment] 2016-05-30 09:32
@allegroLeiden, I thought I could have a try at improving/fixing the 'interpolate in the image plane' type raytrace_1_4, because it sounds like people really like its speed. I remember reading somewhere that you removed it in one of your PRs because it clashed with some new changes, but I can't seem to find that PR any more. Or am I imagining things? Is there something I should be aware of when changing raytrace_1_4?

Also, @christianbrinch, there's a currently commented out 'inverse distance weighting' (Shepard's method) interpolation in raytrace_1_4. According to comments it works great but is slow. It looks to me that it could be made a lot faster. Do you think it's worth trying to do that?

**Comment by allegroLeiden** [comment] 2016-05-30 09:53
@tlunttil I have removed that code from a few of my PRs, whenever I have changed the interface to the function traceray(). This is just laziness, so I would not have to alter the (presently unused) code in raytrace_1_4() to match the changes in the call to traceray(). No other reason.

I certainly encourage you to work on it if you want! The only issue of concern is how we eventually merge all these mods to raytrace. It seems a bit over the top to have all the varieties individually selectable via user parameters, but perhaps we want to retain a bit of choice. E.g. I thought we might just retain the choice between the 1.5 traceray() and the new version in #96; but apart from that, ideally I think we should have a single raytrace(), with no other choices in it, incorporating #79, #109 and your cleaned-up code from raytrace_1_4(). What do you think?

**Comment by tlunttil** [comment] 2016-05-30 10:23
I was wondering about that myself. Providing all possible raytracing options to users would be technically easy, but it would also certainly be confusing. I'd rather have only one algorithm that is both fast and accurate, but that's easier said than done. I'm not sure what the best solution here is - maybe people who have used LIME for science have an opinion? How important is speed vs. accuracy. vs smoothness of the image?

Anyway, since #95 is about raytracing being slow, there's one possible speedup to 1.5 raytracing (and its more recent variants). Currently antialiasing parameter (=rays per image pixel) is a constant. Maybe it would make sense to have it vary according to the complexity of 'stuff' inside each pixel? In practice the easiest method would probably be having the number of samples per pixel vary as a function of projected grid points inside each image pixel. Possibly one could even leave some pixels unsampled and fill them with interpolation, though I foresee headaches when trying to smoothly match the interpolated and raytraced parts. Having at least one sample per pixel is a much easier solution.

**Comment by allegroLeiden** [comment] 2016-05-30 10:40
Have you had a look at #79? It does exactly this with the aliasing. I think any sensible merge will tend to make par->alias obsolete.

If we imagine the grid cells projected onto the image pixel grid, and count the number of cells per pixel N, then there are 2 regimes: N<1 and N>1. #79 deals with the second, raytrace_1_4 with the first. The issues are different though. For N>1 we want to get a good average, for N<1 we want the speed advantage.

Me, I would do something like

    for each cell{
      if all vertices within same pixel{
        #79
      }else{
        interpolate
      }
    }

**Comment by tlunttil** [comment] 2016-05-30 11:00
Sorry, I had completely missed #79 somehow. It indeed does what I suggested. I agree that par->antialias shouldn't be something that the user is supposed to control, everything should happen under the hood automatically.

**Comment by ParfenovS** [comment] 2016-05-30 15:19
The speed can be very important if one wants to compute line spectra (see e.g. figure 4 in http://arxiv.org/abs/1605.03729 ), i.e. the flux density in a high number of lines integrated over the image.

**Comment by tlunttil** [comment] 2016-06-02 08:25
I've tried a few different raytracing/interpolation methods. There really is (or can be, depending on model) a large difference in speed between 1.4 and 1.5 RT. I ran tests with the default model, except setting the image resolution to 512x512 pixels. In this case 1.5 raytraces spectra on 4*512^2 ~1e6 lines of sight, while 1.4 only traces 4000 rays and fills the image planes with interpolation. Interpolation is much faster, so the running time of the RT part scales roughly as the ratio of rays traced - in this case a factor of more than a hundred.

As I wrote earlier, I found the interpolation method in 1.4 a bit strange, so I wrote a simple linear interpolation option. I think it produces better looking images (it's also faster, but both methods are fast enough so it doesn't make much difference).

In 1.4 there was also a commented out 'inverse distance weighting' option. I rewrote that one partially to make it faster, but it still is pretty slow - however it does produce smooth images.

For reference, the RT run times for the model with a single thread on my laptop were:

default 1.4 and 1.4 with linear interpolation: ~<1 s 
1.5 (not including PR #79, #96, or #109:  2 m 10 s
1.4 'inverse distance weighting': 1 m 56 s

the whole RT run took ~13 min, so even the slower raytracing options take only a smallish fraction of the total time, but of course the situation changes if the user needs a lot of images (different lines, directions, etc.) of the same model.

Regarding the different interpolation methods, there's also the question of how many rays show be traced, and how should those rays be placed. In these tests the number of rays was the same as the number of (non-sink) grid points and they were uniformly (randomly) distributed over the image area. Another natural option would be to shoot the rays through each grid points, but at least in the default model where the grid points are strongly concentrated in the centre of the model this causes some extra problems (with aliasing etc.).

The attached image shows the brightness temperature of the central channel (velocity offset 0) of the example model with different RT methods. These were run with the -DTEST option, so the grids etc. should be identical in all cases. Clockwise from upper left: inverse distance weighting, linear interpolation, 1.5, default 1.4.

![interp_test](https://cloud.githubusercontent.com/assets/12169106/15738426/7dbc5b2c-28ab-11e6-8fa0-556558e9e048.png)

**Comment by allegroLeiden** [comment] 2016-06-21 10:27
(First parenthetical comment, @tlunttil, did you mean '<1m' rather than '<1s' for the 1.4 run time in your last comment?)

(Secondly, I am a bit curious that the projected cells in your top right image seem much more uniform in size than those at bottom right. Actually, smaller cells in the 'outfield' I can understand but larger ones in the 'infield'?)

I think my position on the whole issue of raytracing and what changes to it should be included in 1.6 is as follows. Firstly I think we can separate fairly orthogonally two areas: (A) the way we process each ray; (B) the distribution of the ensemble of rays on the image plus possible post-raytrace smoothing algorithms (e.g. linear interpolation in the image plane).

Regarding (A): I think it is simple enough, and also desirable, to retain for the user the choice whether to use the 1.5 style Voronoi traceray or the style in PR #96. I know users who are very enthusiastic to gain access to the smoother output of #96, on the other hand it is significantly slower. I can probably speed up the #96 algorithm by some precalculation but I would rather not attempt that until we have better control over the use of memory, which will not be before 1.7. Anyway this choice between smooth and slow is one I think we need at present to retain for the user.

Issue (B): here I think there is no need for choice, but we need to decide on the exact algorithm we present and then someone needs to implement it in a unified PR. I would vote for something which first checks to see how many projected grid points fall in each image pixel, and treats the pixels differently depending on whether the answer was <1 or >1.

<1: I would favour @tlunttil 's linear interpolation algorithm, although I would be interested to see the code. After working on the 3D interpolation algorithm of #96 I have a great respect for the difficulty of coding numerical geometry - specifically of the difficulty of deciding whether a point falls within a given polytope or not.

>1: I would suggest something like the algorithm in #79, although I think if writing this again I would do it with some differences: I would include a ceiling to the number of rays per pixel for a start. The default model has many fewer grid points than image pixels, but this may not always be the case. Where the density of grid points in the model centre results in, say, 100 or more points per pixel, it seems a bit superfluous to trace a ray for each of them.

**Comment by tlunttil** [comment] 2016-06-21 10:43
Answer to the first question: it may be a typo for <10s, in any case it was much less than a minute.

Answer to the second question is basically the second to last paragraph of my previous comment: the version shown here has essentially the same cell size everywhere, because the rays that are used for nodes in the linear interpolation are distributed uniformly on the image plane independently of the distribution of grid points in the model.

**Comment by allegroLeiden** [comment] 2016-06-21 10:53
Ah ok. I didn't understand that you generated new random points independent of the grid. I'm not sure if that is a good idea though - I would have said it oversamples the outfield and undersamples the infield.

**Comment by tlunttil** [comment] 2016-06-21 11:39
I don't think it's a good idea either, but with the very dense set of points interpolation runs into ugly aliasing issues which I didn't have enough time/interest to try solving...

I'm not really all that fond of image plane interpolation in the first place even in regions where projected grid points/pixel. I would prefer 1.5 version and trying to make that as fast as possible.

**Comment by allegroLeiden** [comment] 2016-06-28 12:32
I've coded up my own version now of the '1.4 algorithm' and have added to it the code from #96 which allows smoother tracing of each ray, plus the code from #79 which handles the central pixels better. Profiling results are:

- 1.5 method: 25 s
- 1.5 + #96: 127 s
- 1.4 + #79: 1 s
- 1.4 + #79 + #96: 8 s

A plot comparing the last two follows:

![comparison](https://cloud.githubusercontent.com/assets/10670238/16415350/0c69e740-3d3d-11e6-8d74-d680a8db15bc.png)

**Comment by tlunttil** [comment] 2016-06-28 13:02
The left one is 1.4 with linear interpolation + #79 and the right one uses the smooth rt? Surprising how different they look. These were run with -DTEST, and interpolation nodes are the projected grid points, right?

**Comment by allegroLeiden** [comment] 2016-06-28 13:09
Yes and yes. If you look closely I think you can see where the cell borders match up. I think the great difference in appearance just indicates how crude the 1.5 algorithm is. :smile:

**Comment by tlunttil** [comment] 2016-06-28 13:15
Now I'm confused: I thought the left one was 1.4 + #79 and right one 1.4 + #79 + #96, so they both are image plane interpolation algorithms. But the basic 1.5 isn't.

**Comment by allegroLeiden** [comment] 2016-06-28 13:26
Think of 2 boolean variables: interpolateAlongRay and interpolateImagePlane. 1.4 had (F T). 1.5 had (F F). #96 had (T F). The plot on the left has (T T), the one on the right (F T).

**Comment by tlunttil** [comment] 2016-06-28 13:33
Ok, that's what I thought. I just didn't think it would've indicated anything about the crudeness of 1.5 ;)

Out of general interest, could you also show the (T F) and (F F) (=1.5) images?

**Comment by tlunttil** [comment] 2016-06-28 13:38
Actually, I'm back to being confused: so the left one interpolates along the ray and right on doesn't? That doesn't seem to match with your 15:09 GMT answer. Or maybe I'm being very dense today...

**Comment by allegroLeiden** [comment] 2016-06-28 13:44
Sorry, my bad, in 15:09 I answered only the last 2 of your 3 questions. To be clearer:

- Both plots use the same linear-interpolation variant of 1.4, plus the algorithm from #79. The code for both plots treats the choice of rays, and the interpolation of their values after these are calculated, identically; all that differs between them is how the values for each ray are calculated.
- The LH plot uses the algorithm of #96 for each ray, the RH plot uses the 1.5/master algorithm.
- Yes both with DTEST.
- Yes both use an identical set of image-plane points, i.e. those by projecting the grid onto the image plane.

**Comment by allegroLeiden** [comment] 2016-06-28 13:48
I will post the images, but I am in the middle of a complicated merge at the moment and I want to focus on ti for a while.

**Comment by allegroLeiden** [comment] 2016-06-30 10:01
![tf_and_ff](https://cloud.githubusercontent.com/assets/10670238/16484610/53ea1a62-3eba-11e6-9c1b-de1c13bb1934.png)

TF on the left, FF on the right.

**Comment by tlunttil** [comment] 2016-06-30 11:29
Ok, so it seems that interpolating along the ray makes a huge difference in apparent smoothness. Image plane interpolation doesn't produce quite as good images as raytracing each pixel individually, but I guess the difference in speed is very significant.

Sometime post 1.6 we'll probably need to think of doing something similar for the 'raytracing' that is used in the calculation of level populations...

**Comment by smaret** [comment] 2016-07-19 12:09
Can I close this issue?

**Comment by tlunttil** [comment] 2016-07-19 12:12
Not yet, I'm still working my way through #145. Probably tomorrow.

**Comment by allegroLeiden** [comment] 2016-07-19 12:15
I really appreciate your hard work @tlunttil !

**Comment by smaret** [comment] 2016-08-01 17:24
PR #145 has been merged, so I'm closing this.

**Closed by smaret** 2016-08-01 17:24 UTC
Labels: question
